### ISSUE TITLE
How to embed the slides within index.html of Jekyll theme

### ISSUE THREAD

**Issue by euler16** [lexoyo/jekyll-slideshow#1]
How to embed the slide within a page?

**Comment by lexoyo** [comment]
I see [in this website we do it like this:](http://www.silex.me)
```
<iframe src="http://singchan.github.io/jekyll-slideshow/slides/www.silex.me.html" style="border: none;" width="100%" height="100%"></iframe>
```

**Comment by lexoyo** [comment]
And it loks like @ruyili [uses it like this on his website here](http://ruyili.github.io/) (nice website by the way ;)
```
<iframe src="https://ruyili.github.io/jekyll-slideshow/slides/craftrivia" scrolling="no" style="border: none;" width="225px" height="375px"></iframe>
```

**Comment by RuyiLi** [comment]
thanks c: 
also, thanks for the great tool, saves me a lot of time and works nicely 👍
